# Generated by Django 3.1.5 on 2021-02-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='deploymodel',
            field=models.IntegerField(default='0'),
        ),
    ]
