# Generated by Django 2.1.8 on 2021-01-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='sitetitle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
