# Generated by Django 2.1.8 on 2021-01-18 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_servers_sitetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servers',
            name='deploystatus',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='servers',
            name='deploytime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AddField(
            model_name='servers',
            name='domain',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servers',
            name='region',
            field=models.CharField(default='山西', max_length=200),
        ),
        migrations.AlterField(
            model_name='servers',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='servers',
            name='serveruser',
            field=models.CharField(default='root', max_length=200),
        ),
    ]
