# Generated by Django 2.1.8 on 2021-01-20 02:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20210118_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servers',
            name='id',
        ),
        migrations.AlterField(
            model_name='servers',
            name='servername',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
