# Generated by Django 3.1.5 on 2021-02-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20210203_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='deploymodel',
            field=models.IntegerField(choices=[(0, '整站部署'), (1, '部署index')], default=0, verbose_name='部署方式'),
        ),
    ]
