# Generated by Django 3.1.5 on 2021-01-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20210120_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='icpurl',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='servers',
            name='region',
            field=models.CharField(default='root', max_length=200),
        ),
    ]
