# Generated by Django 3.1.5 on 2021-02-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_auto_20210203_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='deploystatus',
            field=models.IntegerField(choices=[(0, '待部署'), (1, '已部署'), (2, '部署失败')], default=0, verbose_name='部署状态'),
        ),
    ]
