# Generated by Django 2.2.19 on 2021-05-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_auto_20210203_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='version',
            field=models.IntegerField(choices=[(0, '老版本'), (1, '新版本')], default=1, verbose_name='新版本'),
        ),
    ]
