# Generated by Django 2.2.19 on 2021-05-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_servers_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servers',
            old_name='version',
            new_name='deployversion',
        ),
    ]
