# Generated by Django 2.2.19 on 2021-05-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_auto_20210506_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='pid',
            field=models.CharField(default='p1',max_length=200),
        ),
    ]
