# Generated by Django 2.2.19 on 2021-05-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_servers_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='pid',
            field=models.CharField(default='p1', max_length=200),
        ),
    ]
