# Generated by Django 2.2.19 on 2021-05-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0010_auto_20210507_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='pid',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
