# Generated by Django 2.2.19 on 2021-05-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0012_auto_20210507_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='pid',
            field=models.CharField(default='p0', max_length=200),
        ),
    ]
