# Generated by Django 2.2.19 on 2021-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0013_auto_20210507_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='iswww',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否部署www'),
        ),
    ]
